import { TwitterCardProps } from "./components/twitter-card";
import { SidebarOption } from "./types";
import {
  ArcticonsYahooMail,
  CarbonPortfolio,
  ClarityDollarBillLine,
  HugeiconsArtificialIntelligence06,
  MaterialSymbolsBookmarkOutline,
  MaterialSymbolsLightHome,
  MaterialSymbolsNotificationsOutline,
  MaterialSymbolsPerson,
  MaterialSymbolsSearch,
  PhUsers,
  PrimeTwitter,
  RiAdvertisementFill,
  RiSettings5Fill,
  SolarPodcastBold,
  StreamlineInterfaceFileClipboardWorkPlainClipboardTaskListCompanyOffice,
  StreamlineInterfaceSettingMenuHorizontalCircleNavigationDotsThreeCircleButtonHorizontalMenu,
} from "@components/icons/icons";

export const sidebarOptions: SidebarOption[] = [
  {
    name: "Home",
    href: "/",
    icon: MaterialSymbolsLightHome,
  },
  {
    name: "Explore",
    href: "/explore",
    icon: MaterialSymbolsSearch,
  },
  {
    name: "Notifications",
    href: "/notifications",
    icon: MaterialSymbolsNotificationsOutline,
  },
  {
    name: "Messages",
    href: "/messages",
    icon: ArcticonsYahooMail,
  },
  {
    name: "Grok",
    href: "/grok",
    icon: HugeiconsArtificialIntelligence06,
  },
  {
    name: "communities",
    href: "/communities",
    icon: PhUsers,
  },
  {
    name: "Profile",
    href: "/profile",
    icon: MaterialSymbolsPerson,
  },
  {
    name: "Moreoptions",
    popover: true,
    popoverOptions: [
      {
        name: "Lists",
        href: "/lists",
        icon: StreamlineInterfaceFileClipboardWorkPlainClipboardTaskListCompanyOffice,
      },
      {
        name: "Premium",
        href: "/premium",
        icon: PrimeTwitter,
      },
      {
        name: "Saved",
        href: "/saved",
        icon: MaterialSymbolsBookmarkOutline,
      },
      {
        name: "Monetization",
        href: "/monetization",
        icon: ClarityDollarBillLine,
      },
      {
        name: "Advertisements",
        href: "/advertisements",
        icon: RiAdvertisementFill,
      },
      {
        name: "Works",
        href: "/works",
        icon: CarbonPortfolio,
      },
      {
        name: "Spaces",
        href: "/create-your-space",
        icon: SolarPodcastBold,
      },
      {
        name: "settings",
        href: "/settings-and-privacy",
        icon: RiSettings5Fill,
      },
    ],
    icon: StreamlineInterfaceSettingMenuHorizontalCircleNavigationDotsThreeCircleButtonHorizontalMenu,
  },
  {
    name: "Accounts",
    popover: true,
    popoverOptions: [
      {
        name: "Add existing account",
        href: "/add-existing-account",
      },
      {
        name: "Manage accounts",
        href: "/manage-accounts",
      },
      {
        name: "Logout",
        href: "/logout",
      },
    ],
    icon: MaterialSymbolsPerson,
  },
];

export const fakeTweets: TwitterCardProps[] = [
  {
    username: "Moyano",
    avatarUrl: "https://avatars.githubusercontent.com/u/1234567?v=4",
    name: "Pablo Moyano",
    description: "Apoyando la lucha de los trabajadores desde siempre.",
    createdAt: new Date("2022-03-25T14:30:00Z"),
    comments: 25,
    retweets: 100,
    likes: 250,
    plays: 0,
    mediaUrl: "https://picsum.photos/900/900",
  },
  {
    username: "TechGuru",
    avatarUrl: "https://avatars.githubusercontent.com/u/9876543?v=4",
    name: "Tech Enthusiast",
    description: "Exploring the latest in technology and gadgets.",
    createdAt: new Date("2021-11-12T09:45:00Z"),
    comments: 10,
    retweets: 50,
    likes: 120,
    plays: 0,
  },
  {
    username: "NatureLover",
    avatarUrl: "https://avatars.githubusercontent.com/u/2345678?v=4",
    name: "John Doe",
    description: "Nature enthusiast. Love hiking and exploring the wild.",
    createdAt: new Date("2023-06-07T18:15:00Z"),
    comments: 15,
    retweets: 75,
    likes: 180,
    plays: 0,
    mediaUrl: "https://picsum.photos/700/700",
  },
  {
    username: "Foodie",
    avatarUrl: "https://avatars.githubusercontent.com/u/8765432?v=4",
    name: "Sarah Baker",
    description: "Sharing my culinary adventures.",
    createdAt: new Date("2020-01-15T22:10:00Z"),
    comments: 30,
    retweets: 90,
    likes: 210,
    plays: 0,
    mediaUrl: "https://picsum.photos/600/600",
  },
  {
    username: "TravelBug",
    avatarUrl: "https://avatars.githubusercontent.com/u/3456789?v=4",
    name: "Mike Wanderer",
    description: "Wanderlust. Traveling the world one country at a time.",
    createdAt: new Date("2022-08-30T03:20:00Z"),
    comments: 20,
    retweets: 110,
    likes: 300,
    plays: 0,
    mediaUrl: "https://picsum.photos/800/800",
  },
  {
    username: "FitnessFanatic",
    avatarUrl: "https://avatars.githubusercontent.com/u/4567890?v=4",
    name: "Emily Strong",
    description: "Fitness is not a destination, it's a way of life.",
    createdAt: new Date("2021-04-22T12:50:00Z"),
    comments: 50,
    retweets: 200,
    likes: 400,
    plays: 0,
    mediaUrl: "https://picsum.photos/900/700",
  },
  {
    username: "MusicManiac",
    avatarUrl: "https://avatars.githubusercontent.com/u/5678901?v=4",
    name: "DJ Beats",
    description: "Living life one beat at a time.",
    createdAt: new Date("2023-10-18T06:35:00Z"),
    comments: 40,
    retweets: 150,
    likes: 350,
    plays: 0,
    mediaUrl: "https://picsum.photos/850/850",
  },
  {
    username: "CoderLife",
    avatarUrl: "https://avatars.githubusercontent.com/u/6789012?v=4",
    name: "Jane Coder",
    description: "Coding my way through life, one line at a time.",
    createdAt: new Date("2020-07-07T17:25:00Z"),
    comments: 35,
    retweets: 120,
    likes: 280,
    plays: 0,
    mediaUrl: "https://picsum.photos/950/950",
  },
  {
    username: "Bookworm",
    avatarUrl: "https://avatars.githubusercontent.com/u/7890123?v=4",
    name: "Liam Reader",
    description: "Devouring books one page at a time.",
    createdAt: new Date("2021-02-14T20:05:00Z"),
    comments: 5,
    retweets: 30,
    likes: 90,
    plays: 0,
    mediaUrl: "https://picsum.photos/750/750",
  },
  {
    username: "GamerGuy",
    avatarUrl: "https://avatars.githubusercontent.com/u/8901234?v=4",
    name: "Alex Gamer",
    description: "Gaming is not just a hobby, it's a lifestyle.",
    createdAt: new Date("2022-12-01T04:40:00Z"),
    comments: 45,
    retweets: 170,
    likes: 390,
    plays: 0,
    mediaUrl: "https://picsum.photos/700/500",
  },
];
